def first_three_books():
    """
    Return the first three books from predefined list (title, author).
    Demonstrates list slicing.
    Book list's data generated by ChatGPT - GPT-5
    Book list structure: (Title, Author)
    """

    book_list = [
        ("Dune", "Frank Herbert"),("Neuromancer", "William Gibson"),("Snow Crash", "Neal Stephenson"),("The Left Hand of Darkness", "Ursula K. Le Guin"),("Foundation", "Isaac Asimov"),
    ]
    return book_list[0:3]

def student_id():
    """
    Return dictionary mapping student names to student IDs.
    Demonstrates dictionary usage.
    Student data's data generated by ChatGPT - GPT-5
    """
    student_data = {
    "Alice": "S1234",
    "Bob": "S5678",
    "Charlie": "S9101",
}
    return student_data
