def first_three_books():
    # Book list's data generated by ChatGPT - GPT-5
    # Book list (Title, Author)
    book_list = [
        ("Dune", "Frank Herbert"),("Neuromancer", "William Gibson"),("Snow Crash", "Neal Stephenson"),("The Left Hand of Darkness", "Ursula K. Le Guin"),("Foundation", "Isaac Asimov"),
    ]
    return book_list[0:3]

def student_id():
    # Student data's data generated by ChatGPT - GPT-5
    student_data = {
    "Alice": "S1234",
    "Bob": "S5678",
    "Charlie": "S9101",
}
    return student_data
